### ISSUE TITLE
identity only for V

### ISSUE THREAD

**Issue by txa** [txa/substitution#2]
We only need id for V but I failed specialising this (termination checker didn't like it).
This should also simplify the statement and proof of id∘

**Comment by NathanielB123** [comment]
Agda's termination checker is annoying here. It needs to see `id` being called a sort structurally smaller than `T` in the `sucq {q = T} t` case, which isn't the case when `id` is specialised. We can, however, define a polymorphic `id` and then a specialised inlined one without breaking termination:
```
id : Γ ⊨[ q ] Γ
id {Γ = ∅}     =  ∅
id {Γ = Γ , A} = id ^ A

id′ : Γ ⊨[ V ] Γ
id′ = id {q = V}

{-# INLINE id′ #-}

-- ...

sucq {q = T} t      =  t [ id′ ↑ _ ]
```

Similarly, in the `sucq[] {q = T} {x = x} {y = y} {ys = ys}` case, we need to call a `id∘` lemma with a structurally smaller `V`, but this time it's more painful because we need the `xs : Γ ⊨[ q ] Δ` and `id {q = r} ∘ xs : Γ ⊨[ r ⊔ q ] Δ` types to match, so we need some sort of upcasting with `tm*⊔` or pass proof that `r ≡ V` and coerce (not much better than what we have currently)...



EXCEPT, as I was writing this I thought of another work-around. This is very jank, but it turns out that literally just passing `V` to `id∘`, regardless of how it is used, is enough to retain termination. That is
```
id∘ : ∀ {xs : Γ ⊨[ q ] Δ} → Sort → id {q = V} ∘ xs ≡ xs

id∘′ : ∀ {xs : Γ ⊨[ q ] Δ}  → id′ ∘ xs ≡ xs
id∘′ = id∘ V

{-# INLINE id∘′ #-}

-- ...

sucq[] {q = T} {x = x} {y = y} {ys = ys} =
  sucq x [ ys , y ]
  ≡⟨⟩
  x [ id′ ↑ _ ] [ ys , y ]
  ≡⟨ sym ([∘] {x = x}) ⟩
  x [ (id′ ↑ _) ∘  (ys , y) ]
  ≡⟨ cong (λ ρ → x [ ρ ]) ↑∘  ⟩
  x [ id′ ∘  ys  ]
  ≡⟨ cong (λ ρ → x [ ρ ]) (id∘′ {xs = ys}) ⟩
  x [ ys ]
  ∎

-- ...

id∘ {xs = ∅} _ = refl
id∘ {xs = xs , x} _ = cong₂ _,_ (
   id′ ↑ _ ∘ (xs , x)
     ≡⟨ ↑∘ {xs = id′} ⟩
   id′ ∘ xs
     ≡⟨ id∘ {xs = xs} V ⟩
   xs ∎) refl
```

Seems to _just work_. It's definitely a bit jank, but it _does_ simplify the proofs. I'll make a PR and you can decide whether it's worth it.

(Side note, the same trick also works with `id`:
```
id : Sort → Γ ⊨[ V ] Γ
id {Γ = ∅} _     =  ∅
id {Γ = Γ , A} _ = id V ^ A

id′ : Γ ⊨[ V ] Γ
id′ = id V

{-# INLINE id′ #-}
```
)

**Comment by txa** [comment]
That should work but is a bit hacky. Btw, please use the definitions in paper.lagda because I have changed a lot of the notation. If we experiment in a branch that should be ok (ok may be some work merging).
The good thing is that the use of tm⊑ is avoided which simplifies the proof.
